# color overrides
set -ga terminal-overrides ",screen-256color*:Tc"
set-option -g default-terminal "screen-256color"

# get me out!
set -s escape-time 0

# ctrl b is bad. ctrl a is better
unbind C-b
set-option -g perfix C-a
bind-key C-a send-prefix

# idk why everyone does this
set -g status-style 'bg=#333333 fg=#5eacd3'

# don't 0 index. It's so far away and not in order
set -g base-index 0

set -g renumber-windows on

set -g status-keys vi
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi v send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# vim like pane switching
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

bind-key -r | split-window -h
bind-key -r - split-window -v

bind-key -r f run-shell "tmux neww ~/.local/bin/tmux-sessionizer.bash"
